CREATE TABLE issue_time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    minutes INTEGER NOT NULL,
    work_date DATE NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_time_entry_minutes_positive CHECK (minutes > 0),
    CONSTRAINT fk_time_entry_issue FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT fk_time_entry_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
